// src/utils/iconLibrary.ts
import {
  Heart,
  Star,
  Home,
  User,
  Mail,
  Phone,
  Camera,
  Music,
  Play,
  Settings,
  Globe,
  Zap,
  Shield,
  Crown,
  Rocket,
  Coffee,
  Sun,
  Moon,
} from "lucide-react";

export const availableIcons = [
  { name: "Heart", icon: Heart },
  { name: "Star", icon: Star },
  { name: "Home", icon: Home },
  { name: "User", icon: User },
  { name: "Mail", icon: Mail },
  { name: "Phone", icon: Phone },
  { name: "Camera", icon: Camera },
  { name: "Music", icon: Music },
  { name: "Play", icon: Play },
  { name: "Settings", icon: Settings },
  { name: "Globe", icon: Globe },
  { name: "Zap", icon: Zap },
  { name: "Shield", icon: Shield },
  { name: "Crown", icon: Crown },
  { name: "Rocket", icon: Rocket },
  { name: "Coffee", icon: Coffee },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
];
